### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by gerroon** [Prior99/mopidy-subidy#22]
This is not avail with pip, not sure how I can install this. It would be nice if the way to install is mentioned.

thanks

**Comment by Prior99** [comment]
Perhaps I could publish this to pip. Which Linux distribution are you using?

**Comment by gerroon** [comment]
HI

I am on Debian

**Comment by Prior99** [comment]
Ok. I wrote a package for Arch Linux but I am not familiar with packaging for Debian. I think pip might not be the best place for this plugin to be published. It's my understanding that also on Debian the system's package manager should manage the files in `/usr`. When installing dependencies system-wide using pip without a virtual environment it could potentially lead to conflicts. 

Is there some place like the AUR for Debian?

Maybe you can take it from here and prepare a `.deb` package? [My PKGBUILD file for pacman](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mopidy-subidy) might help.

**Comment by weendigo** [comment]
Hi, is there any way to install the plugin on Ubuntu (16.04, planning upgrade to 18:04) please?

**Comment by Prior99** [comment]
Hi, I am not using Debian or Ubuntu and have no insight on how to package it for those. Feel free to add a CI building a `.deb` file or building it on your own, I'd happily accept your Pullrequest.

On a side note: [Mopidy refuses to migrate to Python 3 since some years](https://github.com/mopidy/mopidy/issues/779) and [Python 2 will soon be end of life](https://pythonclock.org). Due to this, Debian (and I guess Ubuntu, too) [will no longer support Mopidy](https://github.com/mopidy/mopidy/issues/779#issuecomment-451041863) in the future. Perhaps you should consider switching to a different setup. Using [Volumio](https://volumio.org) perhaps.

**Comment by jodal** [comment]
Hi! I'm both a core developer of Mopidy and a Debian Developer.

I'd very much like to encourage you to publish this extension to PyPI. There's nothing in this extension that is specific to Arch Linux, so given a release to PyPI it would very likely work out fo the box both on Debian and quite different systems like macOS.

PyPI packages can safely be installed on Debian systems as is, and they are also typically used as the source for packaging Python software as Debian packages. At the very least, all of the Mopidy extensions packaged in Debian and Ubuntu are based on their PyPI releases.

I just submitted PR #32 that modernizes this extension's project setup to match that of other Mopidy extensions. It should make this extension fully ready to be published to PyPI. I left instructions on how to do that in the PR description.

I'm looking forward to seeing this extension at PyPI, so it becomes easier for users not on Arch Linux to install it :-)

**Comment by jodal** [comment]
Since Mopidy-Subidy now is installable from PyPI, the answer to this issue, which is now also documented in the project's readme, is:

```
sudo python3 -m pip install Mopidy-Subidy
```

I guess this issue can be closed.
