### ISSUE TITLE
Directory Browsing only works two directories down

### ISSUE THREAD

**Issue by kyentei** [Prior99/mopidy-subidy#3]
Browsing directories doesn't work multiple directories down. I've tested this using Ario (GTK frontend to mpd) and ncmpc.

For instance, the directory `John Lennon/Imagine` would be browsable, however `John Lennon/Studio Albums/Imagine` is not.

**Comment by Prior99** [comment]
Unfortunately,  this is because of the way Mopidy and Subsonic work. 
Correct me if I am wrong:

Mopidy has no understanding of "Directories". There are artists, albums and songs. Artists have albums and albums have songs. (Maybe I understood the browsing-backend part of mopidy wrong, though) 

Subsonic just recurses through your directories until you find a song and then reads it's metadata, but doesn't use it to build a hierarchy. 

So this plugin (at least the browsing) needs your hierarchy to be Artist/Album/Songs. 

If someone could point out to me on how to properly list the artists as well as all albums for a single artist (which was the problematic part when I tried to implement it this way) in the Subsonic API I would be very grateful as I too needed to change the structure of my library to fit this restriction.

**Comment by kyentei** [comment]
Alright! Thanks for your feedback. It's probably better if I re-organise the albums anyway. I'm rather new to mopidy and subidy, so this information is new to me.

**Comment by Prior99** [comment]
Please do not close this issue yet. I will have a look at it at the weekend. I am not quiet sure if I understood the browsing feature of mopidy correctly. This might be possible.
